development:
  adapter: postgresql
  encoding: unicode
  database: breno_dev
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: breno_test
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: breno_production
  pool: 5
  password:
